# Generated by Django 5.2.4 on 2025-08-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='package_photos/'),
        ),
    ]
