# Generated by Django 5.2.4 on 2025-08-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.IntegerField(default=7, help_text='Number of days'),
            preserve_default=False,
        ),
    ]
