# Generated by Django 4.2 on 2025-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='coords',
            field=models.JSONField(blank=True, help_text='Coordinates as {lat: float, lng: float}', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features (strings)', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for gallery', null=True),
        ),
    ]
